apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hellok8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hellok8s
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
