apiVersion: v1
kind: Service
metadata:
  name: hellok8s
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: hellok8s
